
presentation:
	../generate.sh
	mkdir -p output
	cp -r assets theme output
	mv presentation.html output/index.html

pdf:
	mkdir -p output
	pandoc -t beamer -o output/presentation.pdf presentation.mdown

clean:
	rm -rf presentation.html presentation.pdf output

build: presentation pdf
